"""Prompt 模板"""

from .rag import (
    DOCUMENT_CLASSIFICATION,
    FORM_DOCUMENT_SUMMARY,
    RAG_DOCUMENT_SUMMARY,
    RAG_ANSWER_PROMPT,
    RAG_QUERY_PROMPT,
    RAG_NO_RESULTS_PROMPT
)
from .summary import SIMPLE_SUMMARY

__all__ = [
    "DOCUMENT_CLASSIFICATION",
    "FORM_DOCUMENT_SUMMARY",
    "RAG_DOCUMENT_SUMMARY",
    "RAG_ANSWER_PROMPT",
    "RAG_QUERY_PROMPT",
    "RAG_NO_RESULTS_PROMPT",
    "SIMPLE_SUMMARY"
]
