"""Create all database tables

Revision ID: 049f32709ba2
Revises: cc9baa744c33
Create Date: 2025-11-12 22:21:00.629126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049f32709ba2'
down_revision: Union[str, Sequence[str], None] = 'cc9baa744c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='分類 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分類名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='分類描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False, comment='處室 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='處室名稱'),
    sa.Column('description', sa.Text(), nullable=True, comment='處室描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='使用者 ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='使用者名稱'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='電子郵件'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密碼雜湊值'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='全名'),
    sa.Column('role', sa.Enum('ADMIN', 'DEPT_ADMIN', 'USER', name='userrole'), nullable=False, comment='使用者角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='帳號是否啟用'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='所屬處室 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False, comment='檔案 ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始檔案名稱'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='檔案儲存路徑'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='檔案大小 (bytes)'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='檔案類型 (MIME type)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='filestatus'), nullable=False, comment='檔案處理狀態'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='錯誤訊息'),
    sa.Column('is_vectorized', sa.Boolean(), nullable=False, comment='是否已向量化'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='切分的區塊數量'),
    sa.Column('summary', sa.Text(), nullable=True, comment='檔案內容摘要'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上傳者 ID'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='所屬處室 ID'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='分類 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_files_category_id'), 'files', ['category_id'], unique=False)
    op.create_index(op.f('ix_files_department_id'), 'files', ['department_id'], unique=False)
    op.create_index(op.f('ix_files_status'), 'files', ['status'], unique=False)
    op.create_index(op.f('ix_files_uploader_id'), 'files', ['uploader_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False, comment='活動 ID'),
    sa.Column('activity_type', sa.Enum('LOGIN', 'LOGOUT', 'UPLOAD', 'DOWNLOAD', 'DELETE', 'SEARCH', 'QUERY', 'UPDATE_PROFILE', 'UPDATE_FILE', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', name='activitytype'), nullable=False, comment='活動類型'),
    sa.Column('description', sa.String(length=500), nullable=False, comment='活動描述'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP 位址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User Agent'),
    sa.Column('extra_data', sa.Text(), nullable=True, comment='額外資訊 (JSON 格式)'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者 ID'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='關聯檔案 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_file_id'), 'activities', ['file_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_file_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_files_uploader_id'), table_name='files')
    op.drop_index(op.f('ix_files_status'), table_name='files')
    op.drop_index(op.f('ix_files_department_id'), table_name='files')
    op.drop_index(op.f('ix_files_category_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
