"""Add query_history table

Revision ID: 95e6223e648d
Revises: 20240115_processing
Create Date: 2025-11-13 14:16:13.824030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e6223e648d'
down_revision: Union[str, Sequence[str], None] = '20240115_processing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), nullable=False, comment='查詢歷史 ID'),
    sa.Column('query', sa.Text(), nullable=False, comment='查詢問題'),
    sa.Column('answer', sa.Text(), nullable=False, comment='生成的答案'),
    sa.Column('sources', sa.JSON(), nullable=True, comment='來源文檔 JSON'),
    sa.Column('source_count', sa.Integer(), nullable=False, comment='來源數量'),
    sa.Column('query_type', sa.String(length=50), nullable=False, comment='查詢類型'),
    sa.Column('scope', sa.String(length=50), nullable=False, comment='搜尋範圍'),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='使用的 Token 數量'),
    sa.Column('processing_time', sa.Float(), nullable=False, comment='處理時間（秒）'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='額外資訊 JSON'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='使用者 ID'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='處室 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='建立時間'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新時間'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_department_id'), 'query_history', ['department_id'], unique=False)
    op.create_index(op.f('ix_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment='儲存的檔案名稱（唯一）',
               existing_comment='原始檔案名稱',
               existing_nullable=False)
    op.alter_column('files', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment='原始檔案名稱',
               existing_nullable=False)
    op.alter_column('files', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment='檔案類型 (pdf, docx, txt, md)',
               existing_comment='檔案類型 (MIME type)',
               existing_nullable=False)
    op.alter_column('files', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment='MIME 類型',
               existing_nullable=True)
    op.alter_column('files', 'description',
               existing_type=sa.TEXT(),
               comment='檔案描述',
               existing_nullable=True)
    op.alter_column('files', 'vector_count',
               existing_type=sa.INTEGER(),
               comment='生成的向量數量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('files', 'processing_step',
               existing_type=sa.VARCHAR(length=50),
               comment='當前處理步驟',
               existing_nullable=True)
    op.alter_column('files', 'processing_progress',
               existing_type=sa.INTEGER(),
               comment='處理進度 (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('files', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='處理開始時間',
               existing_nullable=True)
    op.alter_column('files', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='處理完成時間',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='處理完成時間',
               existing_nullable=True)
    op.alter_column('files', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='處理開始時間',
               existing_nullable=True)
    op.alter_column('files', 'processing_progress',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='處理進度 (0-100)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('files', 'processing_step',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='當前處理步驟',
               existing_nullable=True)
    op.alter_column('files', 'vector_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='生成的向量數量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('files', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='檔案描述',
               existing_nullable=True)
    op.alter_column('files', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='MIME 類型',
               existing_nullable=True)
    op.alter_column('files', 'file_type',
               existing_type=sa.VARCHAR(length=50),
               comment='檔案類型 (MIME type)',
               existing_comment='檔案類型 (pdf, docx, txt, md)',
               existing_nullable=False)
    op.alter_column('files', 'original_filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='原始檔案名稱',
               existing_nullable=False)
    op.alter_column('files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment='原始檔案名稱',
               existing_comment='儲存的檔案名稱（唯一）',
               existing_nullable=False)
    op.drop_index(op.f('ix_query_history_user_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_department_id'), table_name='query_history')
    op.drop_table('query_history')
    # ### end Alembic commands ###
