"""add_processing_paths_to_files

Revision ID: e4b73360d110
Revises: 20251119_add_dept
Create Date: 2025-11-20 16:28:22.720066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b73360d110'
down_revision: Union[str, Sequence[str], None] = '20251119_add_dept'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'user_id',
               existing_type=sa.INTEGER(),
               comment='使用者 ID (實際操作者)',
               existing_comment='使用者 ID',
               existing_nullable=False)
    op.alter_column('categories', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='處室 ID')
    op.add_column('files', sa.Column('markdown_path', sa.String(length=500), nullable=True, comment='Markdown 轉換後的檔案路徑'))
    op.add_column('files', sa.Column('summary_path', sa.String(length=500), nullable=True, comment='摘要 JSON 檔案路徑'))
    op.add_column('files', sa.Column('embedding_path', sa.String(length=500), nullable=True, comment='嵌入向量 JSON 檔案路徑'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'embedding_path')
    op.drop_column('files', 'summary_path')
    op.drop_column('files', 'markdown_path')
    op.alter_column('categories', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='處室 ID')
    op.alter_column('activities', 'user_id',
               existing_type=sa.INTEGER(),
               comment='使用者 ID',
               existing_comment='使用者 ID (實際操作者)',
               existing_nullable=False)
    # ### end Alembic commands ###
